---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-elpa-user-secret
  namespace: elpa-elpa4
spec:
  encryptedData:
    PASSWORD: AgBDbVt/ooOLEBvYLW+JOqNAjbTU2XOdcGJrIOo93vWADS854aYAf+1cP9azFQwhWkTxxEZUl/qir6dLESNpSakSAviV7KvLwAYzdBJktKzNnH3MOFtyjPbHTP6UzpQzPDw5PEL2bl72VANDjAFteqlnMjgBI9rsyCrqY5VXo8gdzDDVsiUa+Eh2BjRwHMz2QTHG0DbjGEzP8PV6OnAnEfS0f4WU91Nr6o9HEmcHNnix54Z7gvebWnrilKv0mppTB3RhTxIFenXFpWvWlwl1QPS/F/merZHb49j44yc2pR+Cnyp7Tcy/4tSANpbDKkgl8/spyoqiLIVOrHeME3NLXGqm85mE6S5mW1rLGZQV1bY0jBk9TwikeCOc+bmL/ZqxV7GL+ocf637+01zA6bBCemtOsi3Pg5xejRqmWJ+rswAG+8Gr58i59PQCmv4pYugK0DmzituEtFsScaxXkiDzetNPbGM1N/yVsOROha8EgohmvAN9AjoRaNxByl7RRE6WDlPuEqDbOfU5kUH9uMn0aBrMFm4eKlVUq5vbxfxQX2KXUYyTZ0CcPl2i9lzqYQiG0TPaPZFbnQwIDBJfKk/79QaZ/iZSf0Z2UkzgVKzbKzyAsLRqyW1PY/mu9/kEKmOAJfRaP08Sgf3jTbIyCGhNJaQAidG1+xvZGHwkhCJva83uUVLUKncbkUPYNqz6VBxSeDJReH4OpFvMaQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dev-elpa-user-secret
      namespace: elpa-elpa4
    type: Opaque
