---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-postgresuser-secret
  namespace: elpa-elpa4
spec:
  encryptedData:
    PASSWORD: AgCtDkZbsQXTFAWPwnAOe7ouzG9UdawTzApYut88ULW221K5GnMQokhwXM6nO+AM0HPtdU8FMmFHTJKpNyZBAM8N7LFMllYNfzXJBTpiPdTMtig3mygv5zRE1GOJux5qtQJ8QC+5Ma7Ga9H7kOf8uD5mM2XIQ27jkPofCfREKTab78hU0dHR9CpTosEytzrq1XEAl8geamG2xMGUL5cLX5dz+g5vnOqO5cCSCC2z/1yklbfAaJjx84SCkdw7xTzLtYXrrL0jQAApxhXhTqU9wolePd4WiZ7HVUz0MXw4JNjoVEz750hhRD40tNtdademBE7m/5NjhkNJwhEYb6BzVElKXcvwu+diBuO5ssP8X1Jfu6pESC1P/OPzITMMACoJa3mY6nmCU+FuEqCym3C9JP/3SiPlS7PrQPPRcbwzjexAPgwWgT2xHF3CMRsM5pKS+gZRafpcSv2p+zZlDuVe65DT8DFTKtAFwgTcrQIShYfBwK6jW0VFNicods62YQeRCNs3fRd/ybfzXUD4DRBzEwK0pdv8Gp374uR67sJ+TO6DLTTd9AXKn7RMkhnl7b3oQnavnN/Jasguy8rHmzirKR9ILtlwMtimScCKjM53Si9+WuoXUtDbkUuWh9wcy9dK41MQB8R2kI/FjSTKaSIGK0Y2bYHOQ/SClkw7/45ueddeA+Uz2PyJ/agJopta7ruBebxVOrxcIzaLlcUJe0yu+tE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dev-postgresuser-secret
      namespace: elpa-elpa4
    type: Opaque
