---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-postgresuser-secret
  namespace: elpa-elpa4
spec:
  encryptedData:
    PASSWORD: AgClxyv01sIcBL7C0UVt2z7sKBYY3eqOqoK+u2aRsXIIrzHBGDmEgpGVtuQYi/Uz9jsjVScFiRtpX3sXgqmYztuSwz/P9LsfkpPbDkvVW4o0RK80qgq+721bmpJV6rp/uGQjb7E1DnDi35pDvnFVBSGHCp2hjNQz2r0/TJDgcPBmNbk4t6eufjjagXbz9OqEruuoFjb42yol2xA/wP/hRCaOEP0SqoM36Cf89HSu7bJ8PQJ8fNPPvqr2NiKUmCXkTDCmXANgDNILKuVizY9n7yf0qxQc3fbmPCBBrVTeX0YER1q6H4jt+I4H3XgBmPJ/TOGcVs9HIvs+m46uQicr17wKSEBXdTdzhGVDlN3As+6GondJ2lsN/2sWNTNNgYC8bxRcD6W2Q8BZm+TvhssXhDERPek8AhEaDJNFshu7SZWF3+JOyap/JG2pJ11HfugsAPT0LrdWyzjU8jxmGeZmHocQxm0L8DMCGRAh8rpzhyULNVclxgZPWRk5XBX/1J0phVusS1q5ebUK8zZuBxyrJEcNZXPahlZnkYbM9iu9er+icBT9+gkmiLwV13FW2MKTsC5zG2PWDlMj6IsPVTREwGjPPEZwuXlG/v75CvvyxSI9zu0TEy8MiadApNaIgk5Ps2sqn6UA1QzYMGxZhpywlkw1KhjycUU0t8I+KxbGjRqXF2OGurDZv/s8I9nsvUTuos19+QLIZW3TqOckFec9dqI=
  template:
    metadata:
      creationTimestamp: null
      name: dev-postgresuser-secret
      namespace: elpa-elpa4
    type: Opaque
