apiVersion: v1
data:
  AUTH_URL: https://employee.login.int.signal-iduna.org/
  AUTH_USERS: S000325,U167653
  DEPLOYMENT_ENV: dev
  ENABLE_JSON_LOGGING: "true"
  JDK_JAVA_OPTIONS: ' -XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=25 -XX:+UseSerialGC
    -XX:+UseStringDeduplication -Ddebug -Dspring.profiles.active=KoP'
  KAFKA_BROKERS: bootstrap-nop.kafka.svc.cluster.local:9443
  KAFKA_OAUTH_TOKEN_ENDPOINT_URL: http://idp-nop.kafka.svc.cluster.local:9443/token
  LOG_LEVEL: INFO
  LOG_LEVEL_SI: DEBUG
  LOGBACK_FILE: logback-json.xml
  OTEL_RESOURCE_ATTRIBUTES: service.name:hint-service,service.version=84761b5.1,deployment.environment=dev
  OTEL_SERVICE_NAME: hint-service
  POSTGRES_SCHEMA_NAME: hin_develop
  POSTGRES_SHOW_SQL: "false"
  POSTGRES_SSL_MODE: prefer
  POSTGRES_URL: jdbc:postgresql://vipsiae11t.system-a.local:5432/elpapgt
  POSTGRES_USER: ZA-SVC-ELPAPG-T
  SERVICE_NAME: hint-service
kind: ConfigMap
metadata:
  name: dev-backend-cm-hint
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
  name: dev-metrics-hint
spec:
  ports:
  - name: http-metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: hint
---
apiVersion: v1
kind: Service
metadata:
  name: dev-service-hint
spec:
  ports:
  - appProtocol: http
    name: http-api
    port: 8080
    targetPort: 8080
  selector:
    app: hint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hint
    environment: dev
  name: dev-app-hint
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hint
      environment: dev
      message: kafka
      sql: postgres
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: hint
        environment: dev
        message: kafka
        sql: postgres
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=$(KAFKA_OAUTH_TOKEN_ENDPOINT_URL)
        - name: KAFKA_OAUTH_CLIENT_ID
          value: workload-client
        - name: KAFKA_OAUTH_CLIENT_SECRET
          value: workload-secret
        - name: KAFKA_SASL_MECHANISM
          value: OAUTHBEARER
        - name: KAFKA_JAAS_ENABLED
          value: "true"
        - name: KAFKA_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_BROKERS
              name: dev-backend-cm-hint
        - name: KAFKA_OAUTH_TOKEN_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              key: KAFKA_OAUTH_TOKEN_ENDPOINT_URL
              name: dev-backend-cm-hint
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: dev-postgresuser-secret
        - name: FLYWAY_ENABLED
          value: "true"
        - name: FLYWAY_LOCATIONS
          value: db/migration
        - name: K8S_ENVIRONMENT_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: KAFKA_CLIENT_ID
          value: $(SERVICE_NAME)-$(K8S_POD_NAME)
        - name: KAFKA_CONSUMER_GROUP
          value: $(SERVICE_NAME)-$(K8S_ENVIRONMENT_LABEL)
        - name: KAFKA_TOPIC_SUFFIX
          value: -$(K8S_ENVIRONMENT_LABEL)
        envFrom:
        - configMapRef:
            name: dev-backend-cm-hint
        image: dev.docker.system.local/elpa-hint-tst/hint:84761b5.1
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/liveness
            port: 8081
          periodSeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
        startupProbe:
          failureThreshold: 9
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 5
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: identity
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dev-dest-rule-hint
spec:
  host: dev-service-hint
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8080
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 8081
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dev-virtualservice-hint
spec:
  gateways:
  - istio-system/mesh-gateway
  - mesh
  hosts:
  - dev-hint-elpa-elpa4.copsinop.de
  - dev-hint.elpa-elpa4.svc.cluster.local
  http:
  - name: dev-hint-route
    route:
    - destination:
        host: dev-service-hint
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dev-virtualservice-metrics-hint
spec:
  gateways:
  - istio-system/mesh-gateway
  - mesh
  hosts:
  - dev-hint-metrics-elpa-elpa4.copsinop.de
  - dev-hint-metrics.elpa-elpa4.svc.cluster.local
  http:
  - route:
    - destination:
        host: dev-metrics-hint
        port:
          number: 8081
