apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: <service-name>-dest-rule
spec:
  host: <env>-<service-name>
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8080
        tls:
          mode: DISABLE
      - port:
          number: 8081
        tls:
          mode: DISABLE
