apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dest-rule-metrics
spec:
  host: prod-metrics-hint
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8081
        tls:
          mode: DISABLE
