apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: application-service
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  selector:
    app: application-service
