apiVersion: v1
data:
  ABW_AUTH_URL_CRM_ROUTING: https://employee.login.abn.signal-iduna.org/
  AUTH_URL: https://employee.login.int.signal-iduna.org/
  AUTH_USER: S000325
  AUTH_USERS: S000325, U066096, S001199, S001200, S000676
  ELPA_URL: https://elpaint.system.local
  ENABLE_JSON_LOGGING: "true"
  JDK_JAVA_OPTIONS: ' -XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=50 -XX:+UseSerialGC
    -Ddebug -Dspring.profiles.active=KoP'
  LOG_LEVEL: INFO
  LOG_LEVEL_SI: DEBUG
  LOGBACK_FILE: logback-json.xml
  POSTGRES_SHOW_SQL: "false"
  POSTGRES_SSL_MODE: prefer
  SERVICE_NAME: application-service
  SWAGGER_ENABLED: "true"
kind: ConfigMap
metadata:
  name: dev-backend-cm-application-service
---
apiVersion: v1
data:
  AUTH_URL: https://employee.login.int.signal-iduna.org/
  ENABLE_JSON_LOGGING: "true"
  JDK_JAVA_OPTIONS: ' -XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=50 -XX:+UseSerialGC
    -Ddebug -Dspring.profiles.active=KoP'
  KAFKA_BROKERS: bootstrap-nop.kafka.svc.cluster.local:9443
  KAFKA_OAUTH_TOKEN_ENDPOINT_URL: http://idp-nop.kafka.svc.cluster.local:9443/token
  LOG_LEVEL: INFO
  LOG_LEVEL_SI: DEBUG
  LOGBACK_FILE: logback-json.xml
  POSTGRES_SCHEMA_NAME: hint
  POSTGRES_SHOW_SQL: "false"
  POSTGRES_SSL_MODE: prefer
  POSTGRES_URL: jdbc:postgresql://vipsiae11t.system-a.local:5432/elpapgt
  POSTGRES_USER: ZA-SVC-ELPAPG-T
  SERVICE_NAME: hint
kind: ConfigMap
metadata:
  name: tst-backend-cm-hint
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
    environment: dev
  name: dev-metrics-application-service
spec:
  ports:
  - name: http-metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: application-service
    environment: dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
  name: dev-service-application-service
spec:
  ports:
  - appProtocol: http
    name: http-api
    port: 8080
    targetPort: 8080
  selector:
    app: application-service
    environment: dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
    environment: tst
  name: tst-metrics-hint
spec:
  ports:
  - name: http-metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: hint
    environment: tst
---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: tst
  name: tst-service-hint
spec:
  ports:
  - appProtocol: http
    name: http-api
    port: 8080
    targetPort: 8080
  selector:
    app: hint
    environment: tst
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application-service
    environment: dev
  name: dev-app-application-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: application-service
      environment: dev
      message: environments
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        signal-iduna.de/prometheus.path: /metrics/prometheus
        signal-iduna.de/prometheus.port: "8081"
        signal-iduna.de/prometheus.scrape: "true"
        traffic.sidecar.istio.io/excludeInboundPorts: 8081,8080
      labels:
        app: application-service
        environment: dev
        message: environments
    spec:
      containers:
      - env:
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: dev-elpa-user-secret
        - name: DEPLOYMENT_ENV
          value: dev
        - name: K8S_ENVIRONMENT_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        envFrom:
        - configMapRef:
            name: dev-backend-cm-application-service
        image: dev.docker.system.local/elpa-application-tst/backend:40ae632.2
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/liveness
            port: 8081
          periodSeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 400m
            memory: 950Mi
          requests:
            cpu: 100m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
        startupProbe:
          failureThreshold: 9
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 5
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: identity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hint
    environment: tst
  name: tst-app-hint
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hint
      environment: tst
      message: environments
      sql: postgres
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        signal-iduna.de/prometheus.path: /metrics/prometheus
        signal-iduna.de/prometheus.port: "8081"
        signal-iduna.de/prometheus.scrape: "true"
        traffic.sidecar.istio.io/excludeInboundPorts: "8081"
      labels:
        app: hint
        environment: tst
        message: environments
        sql: postgres
    spec:
      containers:
      - env:
        - name: DEPLOYMENT_ENV
          value: tst
        - name: JAVA_TOOL_OPTIONS
          value: -Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=$(KAFKA_OAUTH_TOKEN_ENDPOINT_URL)
        - name: KAFKA_OAUTH_CLIENT_ID
          value: workload-client
        - name: KAFKA_OAUTH_CLIENT_SECRET
          value: workload-secret
        - name: KAFKA_SASL_MECHANISM
          value: OAUTHBEARER
        - name: KAFKA_JAAS_ENABLED
          value: "true"
        - name: KAFKA_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_BROKERS
              name: tst-backend-cm-hint
        - name: KAFKA_OAUTH_TOKEN_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              key: KAFKA_OAUTH_TOKEN_ENDPOINT_URL
              name: tst-backend-cm-hint
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: dev-postgresuser-secret
        - name: FLYWAY_ENABLED
          value: "true"
        - name: FLYWAY_LOCATIONS
          value: db/migration
        - name: K8S_ENVIRONMENT_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: KAFKA_CLIENT_ID
          value: $(SERVICE_NAME)-$(K8S_POD_NAME)
        - name: KAFKA_CONSUMER_GROUP
          value: $(SERVICE_NAME)-$(K8S_ENVIRONMENT_LABEL)
        - name: KAFKA_TOPIC_SUFFIX
          value: -$(K8S_ENVIRONMENT_LABEL)
        envFrom:
        - configMapRef:
            name: tst-backend-cm-hint
        image: dev.docker.system.local/elpa-hint-tst/hint:02572fd.10
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health/liveness
            port: 8081
          periodSeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 400m
            memory: 950Mi
          requests:
            cpu: 200m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
        startupProbe:
          failureThreshold: 9
          httpGet:
            path: /health/readiness
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 5
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: identity
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-elpa-user-secret
  namespace: elpa-elpa4
spec:
  encryptedData:
    PASSWORD: AgBDbVt/ooOLEBvYLW+JOqNAjbTU2XOdcGJrIOo93vWADS854aYAf+1cP9azFQwhWkTxxEZUl/qir6dLESNpSakSAviV7KvLwAYzdBJktKzNnH3MOFtyjPbHTP6UzpQzPDw5PEL2bl72VANDjAFteqlnMjgBI9rsyCrqY5VXo8gdzDDVsiUa+Eh2BjRwHMz2QTHG0DbjGEzP8PV6OnAnEfS0f4WU91Nr6o9HEmcHNnix54Z7gvebWnrilKv0mppTB3RhTxIFenXFpWvWlwl1QPS/F/merZHb49j44yc2pR+Cnyp7Tcy/4tSANpbDKkgl8/spyoqiLIVOrHeME3NLXGqm85mE6S5mW1rLGZQV1bY0jBk9TwikeCOc+bmL/ZqxV7GL+ocf637+01zA6bBCemtOsi3Pg5xejRqmWJ+rswAG+8Gr58i59PQCmv4pYugK0DmzituEtFsScaxXkiDzetNPbGM1N/yVsOROha8EgohmvAN9AjoRaNxByl7RRE6WDlPuEqDbOfU5kUH9uMn0aBrMFm4eKlVUq5vbxfxQX2KXUYyTZ0CcPl2i9lzqYQiG0TPaPZFbnQwIDBJfKk/79QaZ/iZSf0Z2UkzgVKzbKzyAsLRqyW1PY/mu9/kEKmOAJfRaP08Sgf3jTbIyCGhNJaQAidG1+xvZGHwkhCJva83uUVLUKncbkUPYNqz6VBxSeDJReH4OpFvMaQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dev-elpa-user-secret
      namespace: elpa-elpa4
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-postgresuser-secret
  namespace: elpa-elpa4
spec:
  encryptedData:
    PASSWORD: AgCtDkZbsQXTFAWPwnAOe7ouzG9UdawTzApYut88ULW221K5GnMQokhwXM6nO+AM0HPtdU8FMmFHTJKpNyZBAM8N7LFMllYNfzXJBTpiPdTMtig3mygv5zRE1GOJux5qtQJ8QC+5Ma7Ga9H7kOf8uD5mM2XIQ27jkPofCfREKTab78hU0dHR9CpTosEytzrq1XEAl8geamG2xMGUL5cLX5dz+g5vnOqO5cCSCC2z/1yklbfAaJjx84SCkdw7xTzLtYXrrL0jQAApxhXhTqU9wolePd4WiZ7HVUz0MXw4JNjoVEz750hhRD40tNtdademBE7m/5NjhkNJwhEYb6BzVElKXcvwu+diBuO5ssP8X1Jfu6pESC1P/OPzITMMACoJa3mY6nmCU+FuEqCym3C9JP/3SiPlS7PrQPPRcbwzjexAPgwWgT2xHF3CMRsM5pKS+gZRafpcSv2p+zZlDuVe65DT8DFTKtAFwgTcrQIShYfBwK6jW0VFNicods62YQeRCNs3fRd/ybfzXUD4DRBzEwK0pdv8Gp374uR67sJ+TO6DLTTd9AXKn7RMkhnl7b3oQnavnN/Jasguy8rHmzirKR9ILtlwMtimScCKjM53Si9+WuoXUtDbkUuWh9wcy9dK41MQB8R2kI/FjSTKaSIGK0Y2bYHOQ/SClkw7/45ueddeA+Uz2PyJ/agJopta7ruBebxVOrxcIzaLlcUJe0yu+tE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dev-postgresuser-secret
      namespace: elpa-elpa4
    type: Opaque
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dev-application-service-dest-rule-application-service
spec:
  host: dev-service-application-service
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8080
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dev-application-service-dest-rule-metrics-application-service
spec:
  host: dev-metrics-application-service
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8081
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tst-dest-rule-hint
spec:
  host: tst-service-hint
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8080
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tst-dest-rule-metrics-hint
spec:
  host: tst-metrics-hint
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8081
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dev-virtual-service-application-service
spec:
  gateways:
  - istio-system/mesh-gateway
  - mesh
  hosts:
  - dev-application-service-elpa-elpa4.copsinop.de
  - dev-application-service.elpa-elpa4.svc.cluster.local
  http:
  - name: dev-application-service-route
    route:
    - destination:
        host: dev-service-application-service
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dev-virtual-service-metrics-application-service
spec:
  gateways:
  - istio-system/mesh-gateway
  - mesh
  hosts:
  - dev-application-service-metrics-elpa-elpa4.copsinop.de
  - dev-application-service-metrics.elpa-elpa4.svc.cluster.local
  http:
  - route:
    - destination:
        host: dev-metrics-application-service
        port:
          number: 8081
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tst-virtual-service-hint
spec:
  gateways:
  - istio-system/mesh-gateway
  - mesh
  hosts:
  - tst-hint-elpa-elpa4.copsinop.de
  - tst-hint.elpa-elpa4.svc.cluster.local
  http:
  - name: tst-route-hint
    route:
    - destination:
        host: tst-service-hint
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tst-virtual-service-metrics-hint
spec:
  gateways:
  - istio-system/mesh-gateway
  - mesh
  hosts:
  - tst-hint-metrics-elpa-elpa4.copsinop.de
  - tst-hint-metrics.elpa-elpa4.svc.cluster.local
  http:
  - name: tst-metrics-route-hint
    route:
    - destination:
        host: tst-metrics-hint
        port:
          number: 8081
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apm-egress
spec:
  egress:
  - ports:
    - port: 4317
      protocol: TCP
    - port: 4318
      protocol: TCP
    to:
    - ipBlock:
        cidr: 172.16.0.0/12
  - ports:
    - port: 5353
      protocol: UDP
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress-gateway
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - istio-system
      podSelector:
        matchLabels:
          environment: dev
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - istio-system
      podSelector:
        matchLabels:
          environment: dev
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-namespace-gateway
spec:
  egress:
  - to:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - elpa-elpa4
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - elpa-elpa4
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-employee-login
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 172.19.80.0/24
    - ipBlock:
        cidr: 172.20.47.40/32
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-postgres
spec:
  egress:
  - ports:
    - port: 5432
      protocol: TCP
    to:
    - ipBlock:
        cidr: 172.19.211.0/24
    - ipBlock:
        cidr: 172.19.89.0/24
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-websphere
spec:
  egress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 172.19.124.0/24
    - ipBlock:
        cidr: 172.19.132.0/24
    - ipBlock:
        cidr: 172.19.226.0/24
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkpolicy-allow-from-otelcollector
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - splunk-otel-collector
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authpolicy-allow-from-ingress-gateway
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        - elpa-elpa4
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authpolicy-allow-from-otelcollector
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - splunk-otel-collector
