apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hint-dest-rule
spec:
  host: abn-hint-service-host
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8080
        tls:
          mode: DISABLE
